require 'sqlite3'
load './models/instance_mapping.rb'

InstanceMapping.create(instance_type: "t3.medium", customer_facing_name: "General (Small)")
InstanceMapping.create(instance_type: "t3.xlarge", customer_facing_name: "General (Medium)")
InstanceMapping.create(instance_type: "t3.2xlarge", customer_facing_name: "General (Large)")
InstanceMapping.create(instance_type: "c5.large", customer_facing_name: "Compute (Small)")
InstanceMapping.create(instance_type: "c5.xlarge", customer_facing_name: "Compute (Medium)")
InstanceMapping.create(instance_type: "c5.2xlarge", customer_facing_name: "Compute (Large)")
InstanceMapping.create(instance_type: "p3.2xlarge", customer_facing_name: "GPU (Small)")
InstanceMapping.create(instance_type: "p3.8xlarge", customer_facing_name: "GPU (Medium)")
InstanceMapping.create(instance_type: "p3.16xlarge", customer_facing_name: "GPU (Large)")
InstanceMapping.create(instance_type: "r5.large", customer_facing_name: "Mem (Small)")
InstanceMapping.create(instance_type: "r5.xlarge", customer_facing_name: "Mem (Medium)")
InstanceMapping.create(instance_type: "r5.2xlarge", customer_facing_name: "Mem (Large)")
InstanceMapping.create(instance_type: "Standard_F2s_v2", customer_facing_name: "Compute (Small)")
InstanceMapping.create(instance_type: "Standard_F4s_v2", customer_facing_name: "Compute (Medium)")
InstanceMapping.create(instance_type: "Standard_F8s_v2", customer_facing_name: "Compute (Large)")
InstanceMapping.create(instance_type: "Standard_NC6s_v3", customer_facing_name: "GPU (Small)")
InstanceMapping.create(instance_type: "Standard_NC24s_v3", customer_facing_name: "GPU (Medium)")
InstanceMapping.create(instance_type: "Standard_E2_v4", customer_facing_name: "Mem (Small)")
InstanceMapping.create(instance_type: "Standard_E4_v4", customer_facing_name: "Mem (Medium)")
InstanceMapping.create(instance_type: "Standard_E8_v2", customer_facing_name: "Mem (Large)")
InstanceMapping.create(instance_type: "Standard_B2s", customer_facing_name: "General (Small)")